### ISSUE TITLE
[Error] Security FIlter

### ISSUE THREAD

**Issue by H4nnhoi** [project-web-chatty/chatty-server#8]
@ohsuhyeon0119 
수현님 시큐리티 테스트하면서 하나 의아한 점이 있네요 지금 signUp과정에는 비인증 api로 처리가 되어야하는데 JWTFilter가 모든 api의 filter로 들어가는 바람에 회원가입이 안되는 것 같습니다

비인증 api 처리에 대해 리팩토링이 필요할 것 같네요

**Comment by ohsuhyeon0119** [comment]
회원가입 저는 되던데 혹시 스웨거로 확인해보신건가요?

**Comment by H4nnhoi** [comment]
스웨거에서 해당 API를 액세스 토큰 제외하고 돌려봤을 때 에러발생합니다. 

그리고 필터 내 로직을 봤을 때 토큰이 없는 상황의 로직이 별도로 보이지 않는데 혹시 제가 놓친부분이 있을까요?
